### ISSUE TITLE
new Repo

### ISSUE THREAD

**Issue by jkriege2** [KiCad/Connectors_Terminal_Blocks.pretty#14]
Hi @SchrodingersGat !

since i started doing the RND terminal blocks (see https://github.com/KiCad/TerminalBlock_RND.pretty/pull/1) ... I also came across some from "Metz Connect" (see http://www.metz-connect.com/de/terminal-blocks-headers/screw-type-terminal-blocks) ... Could you create a repo for these? E.g.  https://github.com/KiCad/TerminalBlock_MetzConnect.pretty) Thanks,
JAN

**Comment by SchrodingersGat** [comment]
https://github.com/KiCad/TerminalBlock_MetzConnect.pretty
