### ISSUE TITLE
Move Terminal Blocks into vendor specific Connectors libraries

### ISSUE THREAD

**Issue by pointhi** [KiCad/Connectors_Terminal_Blocks.pretty#6]
It would be more consistent to use vendor specific `Connectors_xxx.pretty` libraries:
-  `Connectors_Phoenix.pretty` (There is currently a spelling error in the footprint names) 
-  `Connectors_WAGO.pretty`

@ricardocrudo, @CarlPoirier when you say yes, I can do the required rework.

**Comment by evanshultz** [comment]
Hi @pointhi. Can this Issue also be closed? It seems this work has been done, if I understand.

**Comment by SchrodingersGat** [comment]
@pointhi I'm going to close this PR - I'm currently addressing the state of the TerminalBlock libraries
